Do task 8 from tasks-phase1.md
Dove6/tbd-workshop-1 pull request #10
Opened 2024-04-23 02:34 UTC by Dove6

2024-04-23 12:26 UTC, MiniaczQ requested changes
Jeszcze chcę to samemu odpalić

2024-04-23 12:26 UTC, MiniaczQ commented on tasks-phase1.md
> +11. Draw an architecture diagram (e.g. in draw.io) that includes: 🔄
```suggestion
10. Draw an architecture diagram (e.g. in draw.io) that includes: 🔄
```

2024-04-23 12:26 UTC, MiniaczQ commented on tasks-phase1.md
> +12. Create a new PR and add costs by entering the expected consumption into Infracost 🔄
```suggestion
11. Create a new PR and add costs by entering the expected consumption into Infracost 🔄
```

2024-04-23 12:26 UTC, MiniaczQ commented on tasks-phase1.md
> +   ***The port: 8088*** (according to [Google](https://cloud.google.com/dataproc/docs/concepts/accessing/cluster-web-interfaces#available_interfaces_)
```suggestion
   ***The port: 8088*** (according to [Google](https://cloud.google.com/dataproc/docs/concepts/accessing/cluster-web-interfaces#available_interfaces_))
```

2024-04-23 12:26 UTC, MiniaczQ commented on tasks-phase1.md
> +   `127.0.0.1 tbd-cluster-m.c.tbd-2024l-304108.internal. tbd-cluster-m`
Czemu `tbd-cluster-m.c.tbd-2024l-304108.internal.` kropka na końcu?

2024-04-24 08:53 UTC, Dove6 commented on tasks-phase1.md
> +   `127.0.0.1 tbd-cluster-m.c.tbd-2024l-304108.internal. tbd-cluster-m`
DNS root domain.

2024-04-24 17:24 UTC, MiniaczQ approved these changes

2024-04-24 17:25 UTC, merged