Do task 12 from tasks-phase1.md
Dove6/tbd-workshop-1 pull request #11
Opened 2024-04-23 02:49 UTC by Dove6

2024-04-23 12:31 UTC, MiniaczQ approved these changes

2024-04-23 12:32 UTC, MiniaczQ requested changes
Zapomniałem że zmieniły się cyferki

2024-04-23 12:32 UTC, MiniaczQ commented on tasks-phase1.md
> +14. Find and correct the error in spark-job.py 🔄
```suggestion
13. Find and correct the error in spark-job.py 🔄
```

2024-04-23 12:32 UTC, MiniaczQ commented on tasks-phase1.md
> +15. Additional tasks using Terraform: 🔄
```suggestion
14. Additional tasks using Terraform: 🔄
```

2024-04-24 08:57 UTC, Dove6 commented on tasks-phase1.md
> +14. Find and correct the error in spark-job.py 🔄
I hate it

2024-04-24 17:24 UTC, MiniaczQ approved these changes

2024-04-24 17:38 UTC, merged